number = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
}

fraction = { "\\frac{" ~ equation ~ "}{" ~ equation ~ "}" }

sqrt = { "\\sqrt{" ~ equation ~ "}" }
multiply = { "\\cdot" | "*" }
plus = { "+" }
minus = { "-" }
openparen = { "(" }
closedparen = { ")" }
exponent = { "^" } 

equation = {(exponent | openparen | closedparen | sqrt | fraction | multiply | plus | minus|  number)+ } 

WHITESPACE = _{ " " }

